# Generated by Django 2.0.5 on 2019-03-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='model_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
